from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal, Optional
from uuid import uuid4
from pydantic import BaseModel, Field


class RepairType(str, Enum):
    """Supported repair action types categorized by the multi-level hierarchy."""

    NO_REPAIR_REQUIRED = "NO_REPAIR_REQUIRED"
    # Level 1: Extraction-level repairs
    REPAIR_CSS_SELECTORS = "REPAIR_CSS_SELECTORS"
    REPAIR_XPATH_SELECTORS = "REPAIR_XPATH_SELECTORS"
    REPAIR_REGEX_PATTERN = "REPAIR_REGEX_PATTERN"
    REPAIR_TABLE_SCHEMA = "REPAIR_TABLE_SCHEMA"
    REPAIR_EXTRACTION_SCHEMA = "REPAIR_EXTRACTION_SCHEMA"
    SWITCH_EXTRACTION_STRATEGY = "SWITCH_EXTRACTION_STRATEGY"
    REPAIR_SEMANTIC_FILTER = "REPAIR_SEMANTIC_FILTER"
    REPAIR_CHUNKING = "REPAIR_CHUNKING"
    REPAIR_LLM_EXTRACTION_SCHEMA = "REPAIR_LLM_EXTRACTION_SCHEMA"
    REPAIR_CONTENT_TARGET = "REPAIR_CONTENT_TARGET"
    RETRY_WITH_ALTERNATIVE_STRATEGY = "RETRY_WITH_ALTERNATIVE_STRATEGY"
    # Level 2: Scraper / Action / Crawler configuration repairs
    REPAIR_SCRAPER_CONFIG = "REPAIR_SCRAPER_CONFIG"
    REPAIR_ACTION_PLAN = "REPAIR_ACTION_PLAN"
    REPAIR_CRAWLER_CONFIG = "REPAIR_CRAWLER_CONFIG"
    # Level 3: Collector refactor fallback
    BRIGHTDATA_REFACTOR_FALLBACK = "BRIGHTDATA_REFACTOR_FALLBACK"
    # Escalation
    ESCALATE = "ESCALATE"


class RepairStatus(str, Enum):
    """Lifecycle status of a repair proposal."""

    PROPOSED = "proposed"
    APPLIED = "applied"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    ESCALATED = "escalated"


class RepairConfidenceLevel(str, Enum):
    """Confidence tier for accepted repairs determining persistence and probation status."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class RepairFreshnessStatus(str, Enum):
    """Freshness and reliability status of a stored repair memory record."""

    ACTIVE = "active"
    PROBATION = "probation"
    STALE = "stale"
    DISABLED = "disabled"


class PerformanceSnapshot(BaseModel):
    """Quantitative performance snapshot of extraction and validation at a given point in time."""

    health: float = Field(..., ge=0.0, le=1.0, description="Overall health score.")
    quality: float = Field(..., ge=0.0, le=1.0, description="Overall data quality score.")
    records: int = Field(default=0, ge=0, description="Total extracted record count.")
    field_coverage: dict[str, float] = Field(
        default_factory=dict, description="Field name to coverage ratio (0.0 to 1.0)."
    )
    duplicate_rate: float = Field(default=0.0, ge=0.0, le=1.0, description="Duplicate record ratio.")
    schema_valid_rate: float = Field(default=1.0, ge=0.0, le=1.0, description="Schema adherence ratio.")
    strategy_used: str = Field(default="unknown", description="Extraction strategy that produced records.")


class RepairPlan(BaseModel):
    """Structured, evidence-grounded repair plan generated by the Healing Planner."""

    repair_id: str = Field(default_factory=lambda: str(uuid4()))
    repair_type: RepairType = Field(..., description="Target repair category.")
    target_component: Literal["extraction", "scraper", "collector"] = Field(
        default="extraction", description="System component receiving the repair."
    )
    affected_fields: list[str] = Field(
        default_factory=list, description="Specific field names targeted by this repair."
    )
    previous_configuration: dict[str, Any] = Field(
        default_factory=dict, description="Configuration snapshot prior to repair."
    )
    proposed_configuration: dict[str, Any] = Field(
        default_factory=dict, description="New proposed configuration parameters."
    )
    patch: dict[str, Any] = Field(
        default_factory=dict, description="Minimal diff or field-level update instructions."
    )
    reason: str = Field(..., description="Diagnostic reasoning justifying this repair.")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="Confidence in this proposed repair.")
    expected_improvement: dict[str, float] = Field(
        default_factory=dict, description="Projected metric gains (e.g. coverage, health)."
    )
    test_requirements: list[str] = Field(
        default_factory=list, description="Criteria that must be verified during canary execution."
    )
    risk_level: Literal["low", "medium", "high"] = Field(default="low")
    level: int = Field(default=1, ge=1, le=3, description="Hierarchy level: 1=extraction, 2=scraper, 3=collector.")


class RepairCandidate(BaseModel):
    """Ranked candidate repair proposal evaluated during planning."""

    plan: RepairPlan
    score: float = Field(default=0.0, description="Overall ranking score (0.0 to 1.0).")
    rank: int = Field(default=1, ge=1, description="Priority rank among candidates.")
    source: str = Field(default="planner_llm", description="Source of candidate: planner_llm, memory, or fallback.")


class RepairEvaluation(BaseModel):
    """Deterministic validation evaluation comparing before and after performance snapshots."""

    repair_id: str
    before: PerformanceSnapshot
    after: PerformanceSnapshot
    improvement: float = Field(..., description="Delta change in health score (after.health - before.health).")
    critical_failure_resolved: bool = Field(
        default=False, description="True if diagnosis-identified critical failure was eliminated."
    )
    regression_detected: bool = Field(
        default=False, description="True if previously healthy fields or quality metrics degraded."
    )
    accepted: bool = Field(default=False, description="True if repair meets all acceptance criteria.")
    rejection_reason: Optional[str] = Field(
        default=None, description="Detailed explanation if repair was rejected."
    )
    confidence_score: float = Field(default=0.85, ge=0.0, le=1.0, description="Calculated repair confidence score.")
    confidence_level: RepairConfidenceLevel = Field(
        default=RepairConfidenceLevel.HIGH, description="Confidence tier: high, medium, or low."
    )
    multi_page_evaluated: bool = Field(default=False, description="True if validated across multiple pages.")
    multi_page_results: list[dict[str, Any]] = Field(
        default_factory=list, description="Multi-page canary validation metrics."
    )


class RepairMemoryRecord(BaseModel):
    """Persistent representation of an accepted repair pattern associated with a domain signature."""

    memory_id: str = Field(default_factory=lambda: str(uuid4()))
    domain: str
    signature: str = Field(..., description="Stable DOM/structure signature hash.")
    root_cause: str
    repair_type: RepairType
    successful_patch: dict[str, Any]
    health_before: float
    health_after: float
    strategy: str
    provider: str = "local"
    status: RepairFreshnessStatus = Field(default=RepairFreshnessStatus.ACTIVE)
    confidence_level: RepairConfidenceLevel = Field(default=RepairConfidenceLevel.HIGH)
    success_count: int = Field(default=1, ge=0)
    failure_count: int = Field(default=0, ge=0)
    last_used_at: Optional[str] = None
    structural_fingerprint: Optional[str] = None
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
